/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustModelRouteImport } from './routes/trust-model'
import { Route as TreasuryRouteImport } from './routes/treasury'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as SubmittedRouteImport } from './routes/submitted'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CounterpartiesRouteImport } from './routes/counterparties'
import { Route as CeremonyRouteImport } from './routes/ceremony'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsTrustRouteImport } from './routes/docs/trust'
import { Route as DocsQuickstartRouteImport } from './routes/docs/quickstart'
import { Route as DocsProtocolRouteImport } from './routes/docs/protocol'
import { Route as DocsFaqRouteImport } from './routes/docs/faq'
import { Route as DocsConsoleRouteImport } from './routes/docs/console'
import { Route as DocsApiRouteImport } from './routes/docs/api'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'

const TrustModelRoute = TrustModelRouteImport.update({
  id: '/trust-model',
  path: '/trust-model',
  getParentRoute: () => rootRouteImport,
} as any)
const TreasuryRoute = TreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmittedRoute = SubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CounterpartiesRoute = CounterpartiesRouteImport.update({
  id: '/counterparties',
  path: '/counterparties',
  getParentRoute: () => rootRouteImport,
} as any)
const CeremonyRoute = CeremonyRouteImport.update({
  id: '/ceremony',
  path: '/ceremony',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsTrustRoute = DocsTrustRouteImport.update({
  id: '/docs/trust',
  path: '/docs/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: '/docs/quickstart',
  path: '/docs/quickstart',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsProtocolRoute = DocsProtocolRouteImport.update({
  id: '/docs/protocol',
  path: '/docs/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsFaqRoute = DocsFaqRouteImport.update({
  id: '/docs/faq',
  path: '/docs/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsConsoleRoute = DocsConsoleRouteImport.update({
  id: '/docs/console',
  path: '/docs/console',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/apply': typeof ApplyRoute
  '/architecture': typeof ArchitectureRoute
  '/ceremony': typeof CeremonyRoute
  '/counterparties': typeof CounterpartiesRoute
  '/dashboard': typeof DashboardRoute
  '/payroll': typeof PayrollRoute
  '/settings': typeof SettingsRoute
  '/submitted': typeof SubmittedRoute
  '/transfers': typeof TransfersRoute
  '/treasury': typeof TreasuryRoute
  '/trust-model': typeof TrustModelRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/console': typeof DocsConsoleRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/protocol': typeof DocsProtocolRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/trust': typeof DocsTrustRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/apply': typeof ApplyRoute
  '/architecture': typeof ArchitectureRoute
  '/ceremony': typeof CeremonyRoute
  '/counterparties': typeof CounterpartiesRoute
  '/dashboard': typeof DashboardRoute
  '/payroll': typeof PayrollRoute
  '/settings': typeof SettingsRoute
  '/submitted': typeof SubmittedRoute
  '/transfers': typeof TransfersRoute
  '/treasury': typeof TreasuryRoute
  '/trust-model': typeof TrustModelRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/console': typeof DocsConsoleRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/protocol': typeof DocsProtocolRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/trust': typeof DocsTrustRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/apply': typeof ApplyRoute
  '/architecture': typeof ArchitectureRoute
  '/ceremony': typeof CeremonyRoute
  '/counterparties': typeof CounterpartiesRoute
  '/dashboard': typeof DashboardRoute
  '/payroll': typeof PayrollRoute
  '/settings': typeof SettingsRoute
  '/submitted': typeof SubmittedRoute
  '/transfers': typeof TransfersRoute
  '/treasury': typeof TreasuryRoute
  '/trust-model': typeof TrustModelRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/console': typeof DocsConsoleRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/protocol': typeof DocsProtocolRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/trust': typeof DocsTrustRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/apply'
    | '/architecture'
    | '/ceremony'
    | '/counterparties'
    | '/dashboard'
    | '/payroll'
    | '/settings'
    | '/submitted'
    | '/transfers'
    | '/treasury'
    | '/trust-model'
    | '/admin/applications'
    | '/docs/api'
    | '/docs/console'
    | '/docs/faq'
    | '/docs/protocol'
    | '/docs/quickstart'
    | '/docs/trust'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/apply'
    | '/architecture'
    | '/ceremony'
    | '/counterparties'
    | '/dashboard'
    | '/payroll'
    | '/settings'
    | '/submitted'
    | '/transfers'
    | '/treasury'
    | '/trust-model'
    | '/admin/applications'
    | '/docs/api'
    | '/docs/console'
    | '/docs/faq'
    | '/docs/protocol'
    | '/docs/quickstart'
    | '/docs/trust'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/apply'
    | '/architecture'
    | '/ceremony'
    | '/counterparties'
    | '/dashboard'
    | '/payroll'
    | '/settings'
    | '/submitted'
    | '/transfers'
    | '/treasury'
    | '/trust-model'
    | '/admin/applications'
    | '/docs/api'
    | '/docs/console'
    | '/docs/faq'
    | '/docs/protocol'
    | '/docs/quickstart'
    | '/docs/trust'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  ApplyRoute: typeof ApplyRoute
  ArchitectureRoute: typeof ArchitectureRoute
  CeremonyRoute: typeof CeremonyRoute
  CounterpartiesRoute: typeof CounterpartiesRoute
  DashboardRoute: typeof DashboardRoute
  PayrollRoute: typeof PayrollRoute
  SettingsRoute: typeof SettingsRoute
  SubmittedRoute: typeof SubmittedRoute
  TransfersRoute: typeof TransfersRoute
  TreasuryRoute: typeof TreasuryRoute
  TrustModelRoute: typeof TrustModelRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  DocsApiRoute: typeof DocsApiRoute
  DocsConsoleRoute: typeof DocsConsoleRoute
  DocsFaqRoute: typeof DocsFaqRoute
  DocsProtocolRoute: typeof DocsProtocolRoute
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  DocsTrustRoute: typeof DocsTrustRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust-model': {
      id: '/trust-model'
      path: '/trust-model'
      fullPath: '/trust-model'
      preLoaderRoute: typeof TrustModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treasury': {
      id: '/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof TreasuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submitted': {
      id: '/submitted'
      path: '/submitted'
      fullPath: '/submitted'
      preLoaderRoute: typeof SubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counterparties': {
      id: '/counterparties'
      path: '/counterparties'
      fullPath: '/counterparties'
      preLoaderRoute: typeof CounterpartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceremony': {
      id: '/ceremony'
      path: '/ceremony'
      fullPath: '/ceremony'
      preLoaderRoute: typeof CeremonyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/trust': {
      id: '/docs/trust'
      path: '/docs/trust'
      fullPath: '/docs/trust'
      preLoaderRoute: typeof DocsTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/quickstart': {
      id: '/docs/quickstart'
      path: '/docs/quickstart'
      fullPath: '/docs/quickstart'
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/protocol': {
      id: '/docs/protocol'
      path: '/docs/protocol'
      fullPath: '/docs/protocol'
      preLoaderRoute: typeof DocsProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/faq': {
      id: '/docs/faq'
      path: '/docs/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocsFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/console': {
      id: '/docs/console'
      path: '/docs/console'
      fullPath: '/docs/console'
      preLoaderRoute: typeof DocsConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  ApplyRoute: ApplyRoute,
  ArchitectureRoute: ArchitectureRoute,
  CeremonyRoute: CeremonyRoute,
  CounterpartiesRoute: CounterpartiesRoute,
  DashboardRoute: DashboardRoute,
  PayrollRoute: PayrollRoute,
  SettingsRoute: SettingsRoute,
  SubmittedRoute: SubmittedRoute,
  TransfersRoute: TransfersRoute,
  TreasuryRoute: TreasuryRoute,
  TrustModelRoute: TrustModelRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  DocsApiRoute: DocsApiRoute,
  DocsConsoleRoute: DocsConsoleRoute,
  DocsFaqRoute: DocsFaqRoute,
  DocsProtocolRoute: DocsProtocolRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsTrustRoute: DocsTrustRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
